Repository googleapis/dotnet-spanner-entity-framework, pull requests merged in 2021-09, with the labels that each got.

#90 chore: add autorelease scripts
  .kokoro/autorelease.bat
  .kokoro/autorelease.sh
  .kokoro/populatesecrets.sh
  .kokoro/release.bat
  .kokoro/release.sh
  Google.Cloud.EntityFrameworkCore.Spanner/Google.Cloud.EntityFrameworkCore.Spanner.csproj
  README.md
  build.sh
  buildrelease.sh
  toolversions.sh
Labels: cla: yes

#94 chore: add history.md
  docs/history.md
Labels: cla: yes

#93 build: split build actions and skip integration tests on prod from forks
  .github/workflows/build-and-test.yml
  .github/workflows/integration-tests-on-emulator.yml
  .github/workflows/integration-tests-on-production.yml
  .gitignore
Labels: cla: yes

#92 test: add test to verify the use of DDL batches
  Google.Cloud.EntityFrameworkCore.Spanner.Tests/MigrationTests/GenerateCreateScriptTest.cs
  Google.Cloud.EntityFrameworkCore.Spanner.Tests/MigrationTests/MigrationMockServerTests.cs
  Google.Cloud.EntityFrameworkCore.Spanner.Tests/MigrationTests/Migrations/20210830_V2.cs
  Google.Cloud.EntityFrameworkCore.Spanner.Tests/MockSpannerServer.cs
  Google.Cloud.EntityFrameworkCore.Spanner.Tests/SpannerMockServerFixture.cs
  Google.Cloud.EntityFrameworkCore.Spanner/Extensions/SpannerDbContextOptionsExtensions.cs
  Google.Cloud.EntityFrameworkCore.Spanner/Infrastructure/Internal/SpannerOptionsExtension.cs
  Google.Cloud.EntityFrameworkCore.Spanner/Migrations/Internal/SpannerMigrationCommandExecutor.cs
  Google.Cloud.EntityFrameworkCore.Spanner/Storage/Internal/SpannerDatabaseCreator.cs
  Google.Cloud.EntityFrameworkCore.Spanner/Storage/Internal/SpannerRelationalConnection.cs
Labels: cla: yes

#99 chore: release EntityFrameworkCore.Spanner v0.2.0
  Google.Cloud.EntityFrameworkCore.Spanner/Google.Cloud.EntityFrameworkCore.Spanner.csproj
  docs/history.md
Labels: cla: yes, autorelease: pending

#110 test: rollback should not clear the _abortNextStatement flag
  Google.Cloud.EntityFrameworkCore.Spanner.Tests/MockSpannerServer.cs
Labels: cla: yes

#116 chore: add new keyword for methods that hide a super class method
  Google.Cloud.EntityFrameworkCore.Spanner/Storage/Internal/SpannerRetriableConnection.cs
  Google.Cloud.EntityFrameworkCore.Spanner/Storage/Internal/SpannerRetriableTransaction.cs
Labels: cla: yes

#115 test: use unicode for random strings
  Google.Cloud.EntityFrameworkCore.Spanner.IntegrationTests/SpannerFixtureBase.cs
Labels: cla: yes

#114 test: use assembly version instead of hard coded string
  Google.Cloud.EntityFrameworkCore.Spanner.Tests/MigrationTests/MigrationMockServerTests.cs
Labels: cla: yes

#118 fix: use build instead of revision in version
  Google.Cloud.EntityFrameworkCore.Spanner.Tests/MigrationTests/MigrationMockServerTests.cs
Labels: cla: yes

#119 chore: oss compliance
  .github/CODEOWNERS
  .github/sync-repo-settings.yaml
Labels: cla: yes

#120 feat: support single stale reads
  Google.Cloud.EntityFrameworkCore.Spanner.IntegrationTests/TransactionTests.cs
  Google.Cloud.EntityFrameworkCore.Spanner.Samples/Snippets/StaleReadSample.cs
  Google.Cloud.EntityFrameworkCore.Spanner.Tests/EntityFrameworkMockServerTests.cs
  Google.Cloud.EntityFrameworkCore.Spanner/Extensions/QueryableExtensions.cs
  Google.Cloud.EntityFrameworkCore.Spanner/Extensions/SpannerDbContextOptionsExtensions.cs
  Google.Cloud.EntityFrameworkCore.Spanner/Storage/Internal/SpannerRetriableCommand.cs
Labels: cla: yes

#121 docs: remove local NuGet pkg instructions
  README.md
Labels: cla: yes

#122 chore: release EntityFrameworkCore.Spanner v1.0.0
  Google.Cloud.EntityFrameworkCore.Spanner/Google.Cloud.EntityFrameworkCore.Spanner.csproj
  README.md
  docs/history.md
Labels: cla: yes, automerge: exact, autorelease: pending

#128 samples: add a quick start sample
  Google.Cloud.EntityFrameworkCore.Spanner.QuickStart/DataModel.sql
  Google.Cloud.EntityFrameworkCore.Spanner.QuickStart/Google.Cloud.EntityFrameworkCore.Spanner.QuickStart.csproj
  Google.Cloud.EntityFrameworkCore.Spanner.QuickStart/QuickStart.cs
  Google.Cloud.EntityFrameworkCore.Spanner.QuickStart/README.md
Labels: cla: yes, samples
